server {
    listen 80;
    server_name 130.210.14.37;

    charset utf-8;
    client_max_body_size 8M;

    access_log /var/log/nginx/olist.access.log;
    error_log  /var/log/nginx/olist.error.log;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml;
    gzip_min_length 1024;

    location /static/ {
        alias /home/ubuntu/olist_dashboard/staticfiles/;
        expires 30d;
        access_log off;
    }

    location / {
        include     uwsgi_params;
        uwsgi_pass  unix:/run/olist/olist.sock;

        uwsgi_read_timeout 60s;
        uwsgi_send_timeout 60s;
    }
}

