-- 20_create_mart_postgres.sql
-- PostgreSQL 16 translation of the SQL Server mart schema (sql/05, 06, 07, 12).
-- Target: read-only serving copy behind the Django dashboard.
--
-- Translation notes (SQL Server -> PostgreSQL):
--   INT IDENTITY(1,1)   -> INT GENERATED BY DEFAULT AS IDENTITY
--                          BY DEFAULT (not ALWAYS) so the surrogate keys
--                          assigned upstream, including the -1 Unknown
--                          members, load unchanged from CSV.
--   BIT                 -> BOOLEAN  (COPY accepts the exported 0/1)
--   DECIMAL(p,s)        -> NUMERIC(p,s)
--   VARCHAR(n)          -> VARCHAR(n)  (kept for fidelity; TEXT is equivalent
--                                       in Postgres and costs nothing extra)
--
-- year/quarter/month/day are unreserved keywords in Postgres and are legal
-- unquoted as column names, so dim_date keeps its original naming.

DROP TABLE IF EXISTS mart.fact_order_items;
DROP TABLE IF EXISTS mart.fact_delivery_reviews;
DROP TABLE IF EXISTS mart.dim_order_status;
DROP TABLE IF EXISTS mart.dim_product;
DROP TABLE IF EXISTS mart.dim_customer;
DROP TABLE IF EXISTS mart.dim_geography;
DROP TABLE IF EXISTS mart.dim_seller;
DROP TABLE IF EXISTS mart.dim_date;


-- ---------------------------------------------------------------
-- Dimensions
-- ---------------------------------------------------------------

CREATE TABLE mart.dim_order_status (
    order_status_sk INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_status    VARCHAR(30) NOT NULL,
    is_delivered    BOOLEAN NOT NULL
);

CREATE TABLE mart.dim_product (
    product_sk   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id   VARCHAR(50) NOT NULL,
    category_pt  VARCHAR(100),
    category_en  VARCHAR(100),
    weight_g     INT,
    length_cm    INT,
    height_cm    INT,
    width_cm     INT
);

CREATE TABLE mart.dim_customer (
    customer_sk        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_unique_id VARCHAR(50) NOT NULL,
    customer_city      VARCHAR(100),
    customer_state     VARCHAR(10),
    rfm_segment        VARCHAR(20)
);

CREATE TABLE mart.dim_geography (
    geography_sk    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zip_code_prefix VARCHAR(20) NOT NULL,
    city            VARCHAR(100),
    state           VARCHAR(10),
    latitude        NUMERIC(18,10),
    longitude       NUMERIC(18,10)
);

-- SCD-2 table; only is_current rows are exported to this serving copy,
-- so the effective/expiry columns are carried but never versioned here.
CREATE TABLE mart.dim_seller (
    seller_sk      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id      VARCHAR(50) NOT NULL,
    seller_city    VARCHAR(100),
    seller_state   VARCHAR(10),
    effective_date DATE NOT NULL,
    expiry_date    DATE NOT NULL,
    is_current     BOOLEAN NOT NULL
);

CREATE TABLE mart.dim_date (
    date_sk       INT PRIMARY KEY,
    full_date     DATE NOT NULL,
    year          INT NOT NULL,
    quarter       INT NOT NULL,
    month         INT NOT NULL,
    month_name    VARCHAR(20) NOT NULL,
    day           INT NOT NULL,
    weekday_name  VARCHAR(20) NOT NULL,
    is_weekend    BOOLEAN NOT NULL,
    is_holiday    BOOLEAN NOT NULL DEFAULT FALSE,
    holiday_name  VARCHAR(50)
);


-- ---------------------------------------------------------------
-- Facts
-- ---------------------------------------------------------------

CREATE TABLE mart.fact_order_items (
    order_item_sk    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id         VARCHAR(50) NOT NULL,
    order_item_id    INT NOT NULL,
    date_sk          INT NOT NULL,
    product_sk       INT NOT NULL,
    seller_sk        INT NOT NULL,
    customer_sk      INT NOT NULL,
    geography_sk     INT NOT NULL,
    order_status_sk  INT NOT NULL,
    price            NUMERIC(18,2),
    freight_value    NUMERIC(18,2),
    freight_pct      NUMERIC(9,4),
    net_contribution NUMERIC(18,2)
);

CREATE TABLE mart.fact_delivery_reviews (
    delivery_review_sk  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id            VARCHAR(50) NOT NULL,
    customer_sk         INT NOT NULL,
    order_status_sk     INT NOT NULL,
    purchase_date_sk    INT NOT NULL,
    review_score        INT,
    estimated_days      INT,
    actual_days         INT,
    delivery_delay_days INT,
    is_late             BOOLEAN,
    is_delivered        BOOLEAN
);
